# -*- coding: utf-8 -*-
"""lvadsusr_193_tusharlohia_pred_ia2_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pZlVU0bJY83BBNX4jrY05mbvFnuIG-R6
"""

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, mean_squared_error, precision_score, f1_score, recall_score, confusion_matrix
from sklearn.preprocessing import MinMaxScaler
import time
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.cluster import KMeans
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

data = pd.read_csv("/content/Mall_Customers.csv")
data

print(data.isnull().sum())

data['Annual Income (k$)'].fillna(data['Annual Income (k$)'].mean(), inplace=True)
data['Spending Score (1-100)'].fillna(data['Spending Score (1-100)'].mean(), inplace=True)

print(data.isnull().sum())

data['Age_Income_Ratio'] = data['Age'] / data['Annual Income (k$)']
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data[['Age', 'Annual Income (k$)', 'Spending Score (1-100)', 'Age_Income_Ratio']])

k_val = range(2, 10)
inertia_value = []
silhouette_scores = []

for k in k_val:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(scaled_data)
    inertia_value.append(kmeans.inertia_)
    silhouette_scores.append(silhouette_score(scaled_data, kmeans.labels_))

print("Silhouette scores\n")
plt.plot(k_val, silhouette_scores, marker='o')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Silhouette Score')
plt.title('Silhouette Scores for Optimal k')
plt.xticks(k_val)
plt.show()

print("Elbow curve\n")
plt.plot(k_val, inertia_value, marker='o')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia')
plt.title('Elbow Curve for Optimal k')
plt.xticks(k_val)
plt.show()

optimal_k = 7
kmeans = KMeans(n_clusters=optimal_k, random_state=42)
kmeans.fit(scaled_data)

cluster_labels = kmeans.predict(scaled_data)

silhouette_avg = silhouette_score(scaled_data, cluster_labels)
print("silhouette score: ",silhouette_avg)

kmeans = KMeans(n_clusters=optimal_k, random_state=42)
kmeans.fit(scaled_data)
cluster_labels = kmeans.predict(scaled_data)


plt.figure(figsize=(8, 6))
for i in range(optimal_k):
    cluster_data = data[cluster_labels == i]
    plt.scatter(cluster_data['Age'], cluster_data['Spending Score (1-100)'], label=f'Cluster {i+1}')
plt.xlabel('Age')
plt.ylabel('Spending Score (1-100)')
plt.title('Clusters of Mall Customers')
plt.legend()
plt.show()

for i in range(optimal_k):
    cluster_data = data[cluster_labels == i]
    print(f"Cluster {i + 1}:")
    print("Number of customers:", len(cluster_data))
    print("Average age:", cluster_data['Age'].mean())
    print("Average annual income:", cluster_data['Annual Income (k$)'].mean())
    print("Average spending score:", cluster_data['Spending Score (1-100)'].mean())
    print("Age distribution:", cluster_data['Age'].describe())
    print("Annual income distribution:", cluster_data['Annual Income (k$)'].describe())
    print("Spending score distribution:", cluster_data['Spending Score (1-100)'].describe())
    print()

#  Target marketing can be achieved by targetting high value products to people between the age group of 32 as they have the most spending score.

#  The products with partcular price range can be promoted to their correponding age group cluster.
#  Promoting products within a suitable price range to the corresponding age group cluster can enhance the likelihood of customer engagement and purchases.
#  By aligning product offerings with the financial capabilities and preferences of different age segments can optimize their marketing strategies